### ISSUE TITLE
Create detailed sitemap

### ISSUE THREAD

**Issue by aminmus** [chasacademydragons/u09-imdb-clone#3]
Create a detailed sitemap of the application.

**Comment by hernqvistdaniel** [comment]
The sitemap structure has been made and can be edited through link in email

**Comment by aminmus** [comment]
@hernqvistdaniel Do you mean the link to the requirements specification? I cannot see a specific link to a sitemap. Did you create one yourself?

I have a draft, but I am looking to flesh it out a little more.

**Comment by aminmus** [comment]
![Sitemap](https://user-images.githubusercontent.com/22122050/55191624-f0eb1200-51a2-11e9-9b08-64e3fe4e8590.PNG)
