### ISSUE TITLE
Edit review maybe should display the original review in the modal?

### ISSUE THREAD

**Issue by hernqvistdaniel** [chasacademydragons/u09-imdb-clone#55]
When clicking Edit button in a review, it is empty, maybe we should implement that it shows the original review in the text-area which makes it easier to edit?

**Comment by aminmus** [comment]
I have checked the reviews edit modal and it is showing the content of the review I clicked on for me. It is not however a textarea so I agree with you on maybe changing that @hernqvistdaniel .

Can you confirm where this happens for you? @hernqvistdaniel

**Comment by hernqvistdaniel** [comment]
The edit-modal is showing up with content on the Develop branch, apparently I was behind 2 commits on stylebranch. Issue resolved.
